# Generated by Django 4.0.3 on 2022-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningjurnal',
            name='casefolding',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='cleaned',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='cleaning',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='normalisasi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='steeming',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='stopword',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningjurnal',
            name='tokenizing',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
