# Generated by Django 4.0.3 on 2022-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0002_learningjurnal_casefolding_learningjurnal_cleaned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningjurnal',
            name='casefolding',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='cleaned',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='cleaning',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='normalisasi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='steeming',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='stopword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningjurnal',
            name='tokenizing',
            field=models.TextField(null=True),
        ),
    ]
